### PR TITLE
Samuel ipsum example to readme

### PR DESCRIPTION
**Pull request by marinko-peso**
samuel ipsum example :punch:

### CODE REVIEW

**Comment by vladimyr** [comment]
I'll cheerfully merge this just please move it outside this fenced code block to separate `readme` section. Something like `## Examples` would do the trick :wink: Reason I'm asking you to do that is because this block is filled with pasted output of `$ duckiesay --help` so it does not get out of sync :bowtie:

**Comment by marinko-peso** [comment]
@vladimyr how about we add it to help output as well?

**Comment by vladimyr** [comment]
Feel free :+1:

**Comment by marinko-peso** [comment]
@vladimyr  its updated :haircut_man:

**Comment by kronicker** [comment]
Wow this repo is advancing at warp speed 🤡

**Pull request merged**
